//! Capability-rooted workspace inspection.

use std::{fs, path::PathBuf, pin::Pin, sync::Arc};

use harness_tool_api::{
    InvalidToolName, ToolCapabilities, ToolExecutionRequest, ToolExecutor, ToolFailure, ToolInput,
    ToolPresentation, ToolResult, ToolSpec,
};

use crate::WorkspaceRoot;

mod bytes;
mod cargo;
mod elf;
mod list;
mod process;
mod read;
mod search;
mod shell;
mod stat;
mod strings;
mod which;
pub use read::{format_read_display, format_read_output};
pub use shell::{ShellWord, parse_shell_words};

pub const NAME: &str = "inspect";

pub const DESCRIPTION: &str = r#"Batch compact inspection jobs. Each command-start line runs as an independent job.

read <path> [range ...] — Print file lines. Ranges are `start+count` or `start-end`; pass several to batch. Quoted paths are supported. Each output line uses the format `<line_number> <anchor_word> <actual_file_content>`. The anchor word is a dictionary-encoded 8-bit hash of that exact line’s content. It is generated by `inspect` and is not part of the file. For example, in `24 bucket let value = 10;`, `24` is the displayed line number, `bucket` is the dictionary word encoding the line hash, and `let value = 10;` is the actual file content. Use `<line_number> <anchor_word>`, such as `24 bucket`, as an `edit_file` anchor. Never copy the line number or anchor word into replacement content. If a line changes, its anchor word may also change, so read the file again before making another edit.


list [path] [--depth <n>] [--exact] — List directory entries. Direct children are shown by default; directories end in `/`, symlinks use `->`, text files show line counts, and other files show rounded whole-unit sizes. `--exact` also shows exact byte sizes for text files and uses exact sizes for other files. Output is limited to 500 entries.

stat <path> [path ...] [--exact] [--metadata] — Show stat-like size, modification time, and permissions without following symlinks. `--exact` prints exact byte sizes and subsecond timestamps. `--metadata` includes uncommon ownership, inode, device, link, access/change time, and block fields.

bytes <path> <offset>+<length> — Read a bounded byte range as contiguous lowercase hex without separators. Recognize it; don't decode it. Your immediate read is usually right. Decode byte by byte only to resolve ambiguity or verify an exact detail. Reads are limited to 16384 bytes; offsets and requested lengths use exact byte counts, while total size uses a rounded whole-unit representation.

byte-search <path> <hex> — Find an exact contiguous hex sequence in a file. Returns exact byte offsets, including overlapping matches; output is limited to 100 offsets.

strings <path> [literal] — Index printable UTF-8 runs of at least four characters and return exact byte offsets. An optional literal filters whole runs. Output is limited to 100 strings and 160 preview characters per string.

elf <path> [summary|sections|segments|symbols [literal]|relocations [literal]|dynamic [literal]|address <virtual>|offset <file>] — Inspect ELF structure without disassembling. The default summary reports class, architecture, endianness, kind, entry mapping, and interpreter. Other queries report exact file/virtual ranges, symbols, relocations, dynamic tags/imports, or translate between virtual addresses and file offsets. Symbol, relocation, and dynamic literals filter output.

search <pattern> [path ...] — Regex search; returns matches with file names grouped once and line numbers. Patterns with regex metacharacters are treated as regex; plain identifiers are literal. Example: `search fn .*(needle|pin) src tests` or `search TODO src --exclude *.generated.rs`. Options: `-F` literal, `-i` ignore-case, `-g/--glob <glob>` include filter, `--exclude <glob>` exclude filter (repeatable), `--files` list paths.

which <query> — Fuzzy-search executable commands in PATH and print command names with resolved paths.

check [pkg ...] [--lib] [--all-targets] — Rust compiler diagnostics grouped by file under the `E0 err lineposition` header. Both flags work independently and together with package names.

test [cargo selectors] [filter ...] [-- libtest options] — Run `cargo test` with compact output. No filter runs the entire selected suite. Multiple positional filters run independently, which stock `cargo test` cannot do in one invocation. Cargo selectors include `-p/--package`, `--workspace`, `--lib`, `--bin`, `--test`, `--doc`, and `--all-targets`. Example: `test -p harness-core module::first module::second -- --exact`.

ps <name> — List processes; pass a name to filter.

pwd — Print working directory."#;

pub const LARK_GRAMMAR: &str = "start: command\ncommand: /(?s).+/";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InspectReadOutputRequest {
    pub path: String,
    pub start_line: usize,
    pub line_count: usize,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InspectReadNextRecord {
    pub start_line: usize,
    pub line_count: usize,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InspectReadDisplayRecord {
    pub path: String,
    pub start_line: usize,
    pub lines: Vec<String>,
    pub next: Option<InspectReadNextRecord>,
}

pub fn edit_line_hash(line: &str) -> u8 {
    let mut hash = 0xcbf2_9ce4_8422_2325_u64;
    for byte in line.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    }
    (hash & 0xff) as u8
}

pub fn line_anchor_word(hash: u8) -> &'static str {
    static CHARS: std::sync::OnceLock<Vec<&'static str>> = std::sync::OnceLock::new();
    let chars = CHARS.get_or_init(|| {
        include_str!("../../../../dictionary.txt")
            .lines()
            .filter_map(|line| {
                let line = line.trim();
                line.strip_prefix('\'')?.strip_suffix('\'')
            })
            .collect()
    });
    if chars.is_empty() {
        return "";
    }
    chars[hash as usize % chars.len()]
}

pub fn spec() -> Result<ToolSpec, InvalidToolName> {
    Ok(ToolSpec::new(NAME)?
        .description(DESCRIPTION)
        .lark(LARK_GRAMMAR)
        .capabilities(ToolCapabilities {
            read_only: true,
            mutates_workspace: false,
            idempotent: true,
        }))
}

pub struct Executor {
    workspace: WorkspaceRoot,
}
impl Executor {
    pub fn new(workspace: WorkspaceRoot) -> Self {
        Self { workspace }
    }
}

::inventory::submit! {
    crate::inventory::ToolRegistration {
        spec,
        executor: |workspace| Arc::new(Executor::new(workspace)),
    }
}
impl ToolExecutor for Executor {
    fn execute(
        &self,
        request: ToolExecutionRequest,
    ) -> Pin<Box<dyn std::future::Future<Output = Result<ToolResult, ToolFailure>> + Send + '_>>
    {
        let result = if request.tool.as_str() != NAME || request.route.identifier != NAME {
            Err(ToolFailure::Execution(
                "executor route does not match `inspect`".into(),
            ))
        } else {
            execute(&self.workspace, &request.input)
        };
        Box::pin(std::future::ready(result))
    }
}

pub fn execute(workspace: &WorkspaceRoot, input: &ToolInput) -> Result<ToolResult, ToolFailure> {
    let lines = input.as_str().lines().collect::<Vec<_>>();
    if lines.iter().all(|line| line.trim().is_empty()) {
        return Err(ToolFailure::InvalidInput(
            "failed to parse `inspect` input: at least one command is required".into(),
        ));
    }
    let mut output_text = String::new();
    let mut index = 0;
    while index < lines.len() {
        let line = lines[index].trim();
        if line.is_empty() {
            index += 1;
            continue;
        }
        if let Some(header) = line.strip_prefix("read ") {
            let mut header_words = parse_shell_words(header).map_err(|e| {
                ToolFailure::InvalidInput(format!("failed to parse `inspect` read input: {e}"))
            })?;
            if header_words.is_empty() {
                return Err(ToolFailure::InvalidInput(
                    "failed to parse `inspect` input: read path is required".into(),
                ));
            }
            let path = header_words.remove(0);
            let mut ranges = header_words
                .into_iter()
                .map(|word| parse_range(&word.value))
                .collect::<Result<Vec<_>, _>>()
                .map_err(ToolFailure::InvalidInput)?;
            index += 1;
            while index < lines.len() {
                let candidate = lines[index].trim();
                if candidate.is_empty() {
                    index += 1;
                    continue;
                }
                if command_start(candidate) {
                    break;
                }
                ranges.push(parse_range(candidate).map_err(ToolFailure::InvalidInput)?);
                index += 1;
            }
            if ranges.is_empty() {
                let (name, file) =
                    resolve(workspace, &path.value).map_err(ToolFailure::InvalidInput)?;
                let text = fs::read(&file)
                    .map_err(|e| format!("inspect read {name}: {e}"))
                    .and_then(|bytes| {
                        String::from_utf8(bytes).map_err(|_| {
                            format!("inspect read {name}: file is not UTF-8; use `bytes`")
                        })
                    })
                    .map_err(ToolFailure::InvalidInput)?;
                let total_lines = text.lines().count();
                let hint = if total_lines > 1000 {
                    format!(
                        "\nfile has {total_lines} lines; read the rest with `read {name} 1001-end`\n"
                    )
                } else {
                    String::new()
                };
                output_text.push_str(&format_read_output(
                    &InspectReadOutputRequest {
                        path: name,
                        start_line: 1,
                        line_count: 1000,
                    },
                    &text,
                ));
                output_text.push_str(&hint);
                continue;
            }
            for (start, count) in ranges {
                let (name, file) =
                    resolve(workspace, &path.value).map_err(ToolFailure::InvalidInput)?;
                let text = fs::read(&file)
                    .map_err(|e| format!("inspect read {name}: {e}"))
                    .and_then(|bytes| {
                        String::from_utf8(bytes).map_err(|_| {
                            format!("inspect read {name}: file is not UTF-8; use `bytes`")
                        })
                    })
                    .map_err(ToolFailure::InvalidInput)?;
                output_text.push_str(&format_read_output(
                    &InspectReadOutputRequest {
                        path: name,
                        start_line: start,
                        line_count: count,
                    },
                    &text,
                ));
            }
            continue;
        }
        let words = parse_shell_words(line).map_err(|e| {
            ToolFailure::InvalidInput(format!("failed to parse `inspect` input: {e}"))
        })?;
        output_text
            .push_str(&execute_command(workspace, &words).map_err(ToolFailure::InvalidInput)?);
        index += 1;
    }
    Ok(output(output_text, "inspect"))
}

fn execute_command(workspace: &WorkspaceRoot, words: &[ShellWord]) -> Result<String, String> {
    let Some(command) = words.first().map(|word| word.value.as_str()) else {
        return Ok(String::new());
    };
    match command {
        "pwd" if words.len() == 1 => Ok(format!("{}\n", workspace.path().display())),
        "list" | "ls" => list::execute(workspace, &words[1..]),
        "stat" => stat::execute(workspace, &words[1..]),
        "bytes" => bytes::execute(workspace, &words[1..]),
        "byte-search" => bytes::search(workspace, &words[1..]),
        "strings" => strings::execute(workspace, &words[1..]),
        "elf" => elf::execute(workspace, &words[1..]),
        "search" => search::execute(workspace, &words[1..]),
        "which" => which::execute(&words[1..]),
        "check" => cargo::check(workspace, &words[1..]),
        "test" => cargo::test(workspace, &words[1..]),
        "ps" => process::execute(&words[1..]),
        other => Err(format!(
            "failed to parse `inspect` input: unsupported command `{other}`"
        )),
    }
}

fn command_start(line: &str) -> bool {
    let command = line.split_whitespace().next().unwrap_or_default();
    matches!(
        command,
        "pwd"
            | "list"
            | "ls"
            | "stat"
            | "bytes"
            | "byte-search"
            | "strings"
            | "elf"
            | "search"
            | "which"
            | "check"
            | "test"
            | "ps"
            | "read"
    )
}

fn parse_range(value: &str) -> Result<(usize, usize), String> {
    if let Some((start, count)) = value.split_once('+') {
        let start = shell::parse_positive_usize_value(start).map_err(|_| {
            "failed to parse `inspect` input: range start must be a positive integer".to_string()
        })?;
        let count = shell::parse_positive_usize_value(count).map_err(|_| {
            "failed to parse `inspect` input: range count must be a positive integer".to_string()
        })?;
        return Ok((start, count));
    }
    if let Some((start, end)) = value.split_once('-') {
        let start = shell::parse_positive_usize_value(start).map_err(|_| {
            "failed to parse `inspect` input: range start must be a positive integer".to_string()
        })?;
        let count = if end.eq_ignore_ascii_case("end") {
            usize::MAX
        } else {
            let end = shell::parse_positive_usize_value(end).map_err(|_| {
                "failed to parse `inspect` input: range end must be a positive integer or `end`"
                    .to_string()
            })?;
            if end < start {
                return Err("failed to parse `inspect` input: range end must be >= start".into());
            }
            end - start + 1
        };
        return Ok((start, count));
    }
    Err("failed to parse `inspect` input: range must be `start+count` or `start-end`".into())
}

fn output(text: impl Into<String>, label: &str) -> ToolResult {
    let text = text.into();
    ToolResult {
        model_output: text.clone(),
        presentation: Some(ToolPresentation {
            label: label.into(),
            display: Some(text),
        }),
        artifacts: Vec::new(),
    }
}
fn resolve(workspace: &WorkspaceRoot, value: &str) -> Result<(String, PathBuf), String> {
    let relative = workspace
        .relative_path(value)
        .map_err(|e| format!("inspect: invalid path `{value}`: {e}"))?;
    let name = relative.as_str().to_owned();
    let abs = workspace.path().join(relative.as_str());

    // If the path already exists, return it directly.
    if abs.exists() {
        return Ok((name, abs));
    }

    // Path does not exist — try to suggest a correction.
    if let Some(correction) = crate::path_correction::suggest_correction(workspace.path(), &name) {
        let mut msg = format!("inspect: path `{name}` does not exist");
        msg.push_str(&format!("\nDid you mean: `{}`?", correction.suggested));
        if !correction.listing.is_empty() {
            msg.push_str(&format!(
                "\nFiles in `{}`:",
                correction.deepest_prefix,
            ));
            for entry in &correction.listing {
                msg.push_str(&format!("\n  {entry}"));
            }
        }
        msg.push('\n');
        return Err(msg);
    }

    Err(format!("inspect: path `{name}` does not exist\n"))
}

pub(crate) fn positive(value: &str, command: &str) -> Result<usize, String> {
    value
        .parse()
        .ok()
        .filter(|v| *v > 0)
        .ok_or_else(|| format!("inspect {command}: expected a positive integer"))
}
