//! Capability-rooted workspace inspection.

use std::{path::PathBuf, pin::Pin};

use harness_tool_api::{
    InspectJobOutcome, InspectJobRequest, InspectJobSuccess, InspectRequest, InspectResult,
    LineRange, Prepared, ToolCapabilities, ToolExecutionFailure, ToolExecutionRequest,
    ToolExecutor, ToolFailure, ToolFailureCategory, ToolInvocation, ToolOutcome,
    ToolPreparationRequest, ToolResult, ToolSpec, InvalidToolName,
};

use crate::WorkspaceRoot;

mod bytes;
mod cargo;
mod elf;
mod list;
mod process;
mod read;
mod search;
mod shell;
mod stat;
mod strings;
mod which;
pub use shell::{ShellWord, parse_shell_words};

pub const NAME: &str = "inspect";

pub const DESCRIPTION: &str = r#"Batch compact inspection jobs. Each command-start line runs as an independent job.

read <path> [range ...] — Print file lines. Ranges are `start+count` or `start-end`; pass several to batch. Quoted paths are supported. Each output line uses the format `<line_number> <anchor_word> <actual_file_content>`. The anchor word is a dictionary-encoded 8-bit hash of that exact line’s content. It is generated by `inspect` and is not part of the file. For example, in `24 bucket let value = 10;`, `24` is the displayed line number, `bucket` is the dictionary word encoding the line hash, and `let value = 10;` is the actual file content. Use `<line_number> <anchor_word>`, such as `24 bucket`, as an `edit_file` anchor. Never copy the line number or anchor word into replacement content. If a line changes, its anchor word may also change, so read the file again before making another edit.


list [path] [--depth <n>] [--exact] — List directory entries. Direct children are shown by default; directories end in `/`, symlinks use `->`, text files show line counts, and other files show rounded whole-unit sizes. `--exact` also shows exact byte sizes for text files and uses exact sizes for other files. Output is limited to 500 entries.

stat <path> [path ...] [--metadata] — Show stat-like size, modification time, and permissions without following symlinks. `--metadata` includes uncommon ownership, inode, device, link, access/change time, and block fields.

bytes <path> <offset>+<length> — Read a bounded byte range as contiguous lowercase hex without separators. Recognize it; don't decode it. Your immediate read is usually right. Decode byte by byte only to resolve ambiguity or verify an exact detail. Reads are limited to 16384 bytes; offsets and requested lengths use exact byte counts, while total size uses a rounded whole-unit representation.

byte-search <path> <hex> — Find an exact contiguous hex sequence in a file. Returns exact byte offsets, including overlapping matches; output is limited to 100 offsets.

strings <path> [literal] — Index printable UTF-8 runs of at least four characters and return exact byte offsets. An optional literal filters whole runs. Output is limited to 100 strings and 160 preview characters per string.

elf <path> [summary|sections|segments|symbols [literal]|relocations [literal]|dynamic [literal]|address <virtual>|offset <file>] — Inspect ELF structure without disassembling. The default summary reports class, architecture, endianness, kind, entry mapping, and interpreter. Other queries report exact file/virtual ranges, symbols, relocations, dynamic tags/imports, or translate between virtual addresses and file offsets. Symbol, relocation, and dynamic literals filter output.

search <pattern> [path/glob ...] — Regex search; returns matches with file names grouped once and line numbers. Positional wildcards constrain paths without shell expansion. Common `rg` forms are supported: `-e/--regexp`, `-F/--fixed-strings`, `-i/--ignore-case`, `-s/--case-sensitive`, `-S/--smart-case`, `-g/--glob`, `-l/--files-with-matches`, `--exclude`, `--files`, and `--`. `--files` lists searchable paths without requiring a pattern. Output defaults to 100 results; use `--max <n>` to change it.

which <query> — Fuzzy-search executable commands in PATH and print command names with resolved paths.

check [pkg ...] [--lib] [--all-targets] — Rust compiler diagnostics grouped by file under the `E0 err lineposition` header. Both flags work independently and together with package names.

test [cargo selectors] [filter ...] [-- libtest options] — Run `cargo test` with compact output. No filter runs the entire selected suite. Multiple positional filters run independently, which stock `cargo test` cannot do in one invocation. Cargo selectors include `-p/--package`, `--workspace`, `--lib`, `--bin`, `--test`, `--doc`, and `--all-targets`. Example: `test -p harness-core module::first module::second -- --exact`.

ps <name> — List processes; pass a name to filter.

pwd — Print working directory."#;

pub const LARK_GRAMMAR: &str = "start: command\ncommand: /(?s).+/";

pub(super) struct InspectCommandOutput {
    model: String,
    result: InspectJobSuccess,
}

pub fn edit_line_hash(line: &str) -> u8 {
    let mut hash = 0xcbf2_9ce4_8422_2325_u64;
    for byte in line.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    }
    (hash & 0xff) as u8
}

pub fn line_anchor_word(hash: u8) -> &'static str {
    static CHARS: std::sync::OnceLock<Vec<&'static str>> = std::sync::OnceLock::new();
    let chars = CHARS.get_or_init(|| {
        include_str!("../../../../dictionary.txt")
            .lines()
            .filter_map(|line| {
                let line = line.trim();
                line.strip_prefix('\'')?.strip_suffix('\'')
            })
            .collect()
    });
    if chars.is_empty() {
        return "";
    }
    chars[hash as usize % chars.len()]
}

pub fn spec() -> Result<ToolSpec, InvalidToolName> {
    Ok(ToolSpec::new(NAME)?
        .description(DESCRIPTION)
        .lark(LARK_GRAMMAR)
        .capabilities(ToolCapabilities {
            read_only: true,
            mutates_workspace: false,
            idempotent: true,
        }))
}

pub struct Executor {
    workspace: WorkspaceRoot,
}
impl Executor {
    pub fn new(workspace: WorkspaceRoot) -> Self {
        Self { workspace }
    }
}

impl ToolExecutor for Executor {
    fn prepare(&self, request: ToolPreparationRequest) -> Result<ToolInvocation, ToolFailure> {
        if request.tool.as_str() != NAME || request.route.identifier != NAME {
            return Err(ToolFailure::Execution(format!(
                "executor route does not match `{NAME}` for tool {}",
                request.tool.as_str()
            )));
        }
        let input = match request.input.decode_freeform() {
            Ok(input) => input,
            Err(error) => {
                return Ok(ToolInvocation::Inspect(Prepared::Rejected(
                    harness_tool_api::ToolInputRejection {
                        message: error.to_string(),
                    },
                )));
            }
        };
        let prepared = match prepare_input(&input) {
            Ok(request) => Prepared::Ready(request),
            Err(message) => {
                Prepared::Rejected(harness_tool_api::ToolInputRejection { message })
            }
        };
        Ok(ToolInvocation::Inspect(prepared))
    }

    fn execute(
        &self,
        request: ToolExecutionRequest,
    ) -> Pin<Box<dyn std::future::Future<Output = Result<ToolResult, ToolFailure>> + Send + '_>>
    {
        if request.tool.as_str() != NAME || request.route.identifier != NAME {
            return Box::pin(std::future::ready(Err(ToolFailure::Execution(format!(
                "executor route does not match `{NAME}` for tool {}",
                request.tool.as_str()
            )))));
        }

        let workspace = self.workspace.clone();
        Box::pin(async move {
            let prepared = match request.invocation {
                ToolInvocation::Inspect(Prepared::Ready(prepared)) => prepared,
                ToolInvocation::Inspect(Prepared::Rejected(rejection)) => {
                    return Ok(rejected_result(rejection.message));
                }
                invocation => {
                    return Err(ToolFailure::Execution(format!(
                        "`{NAME}` received prepared invocation for `{}`",
                        invocation.tool().name()
                    )));
                }
            };
            tokio::task::spawn_blocking(move || execute(&workspace, &prepared))
                .await
                .map_err(|error| ToolFailure::Execution(error.to_string()))
        })
    }
}

fn prepare_input(input: &str) -> Result<InspectRequest, String> {
    let lines = input.lines().collect::<Vec<_>>();
    if lines.iter().all(|line| line.trim().is_empty()) {
        return Err("failed to parse `inspect` input: at least one command is required".into());
    }

    let mut jobs = Vec::new();
    let mut index = 0;
    while index < lines.len() {
        let line = lines[index].trim();
        if line.is_empty() {
            index += 1;
            continue;
        }

        if let Some(header) = line.strip_prefix("read ") {
            let mut words = parse_shell_words(header)
                .map_err(|error| format!("failed to parse `inspect` read input: {error}"))?;
            if words.is_empty() {
                return Err("failed to parse `inspect` input: read path is required".into());
            }
            let path = words.remove(0).value;
            let mut ranges = words
                .iter()
                .map(|word| parse_range(&word.value))
                .collect::<Result<Vec<_>, _>>()?;
            index += 1;
            while index < lines.len() {
                let candidate = lines[index].trim();
                if candidate.is_empty() {
                    index += 1;
                    continue;
                }
                if command_start(candidate) {
                    break;
                }
                ranges.push(parse_range(candidate)?);
                index += 1;
            }
            jobs.push(InspectJobRequest::Read(
                harness_tool_api::InspectReadRequest { path, ranges },
            ));
            continue;
        }

        let words = parse_shell_words(line)
            .map_err(|error| format!("failed to parse `inspect` input: {error}"))?;
        jobs.push(prepare_command(&words)?);
        index += 1;
    }

    Ok(InspectRequest { jobs })
}

fn prepare_command(words: &[ShellWord]) -> Result<InspectJobRequest, String> {
    let Some(command) = words.first().map(|word| word.value.as_str()) else {
        return Err("failed to parse `inspect` input: command is required".into());
    };
    let args = &words[1..];
    match command {
        "read" => Err("failed to parse `inspect` input: usage: `read <path> [range ...]`".into()),
        "list" => list::prepare(args).map(InspectJobRequest::List),
        "stat" => stat::prepare(args).map(InspectJobRequest::Stat),
        "bytes" => bytes::prepare(args).map(InspectJobRequest::Bytes),
        "byte-search" => bytes::prepare_search(args).map(InspectJobRequest::ByteSearch),
        "strings" => strings::prepare(args).map(InspectJobRequest::Strings),
        "elf" => elf::prepare(args).map(InspectJobRequest::Elf),
        "search" => search::prepare(args).map(InspectJobRequest::Search),
        "which" => which::prepare(args).map(InspectJobRequest::Which),
        "check" => cargo::prepare_check(args).map(InspectJobRequest::Check),
        "test" => cargo::prepare_test(args).map(InspectJobRequest::Test),
        "ps" => process::prepare(args).map(InspectJobRequest::Ps),
        "pwd" if args.is_empty() => Ok(InspectJobRequest::Pwd),
        "pwd" => Err("failed to parse `inspect` input: usage: `pwd`".into()),
        other => Err(format!(
            "failed to parse `inspect` input: unsupported command `{other}`"
        )),
    }
}

fn execute(workspace: &WorkspaceRoot, request: &InspectRequest) -> ToolResult {
    let mut model_output = String::new();
    let mut jobs = Vec::with_capacity(request.jobs.len());
    for job in &request.jobs {
        match execute_job(workspace, job) {
            Ok(output) => {
                model_output.push_str(&output.model);
                jobs.push(InspectJobOutcome::Succeeded(output.result));
            }
            Err(message) => {
                model_output.push_str(&message);
                if !message.ends_with('\n') {
                    model_output.push('\n');
                }
                jobs.push(InspectJobOutcome::Failed(ToolExecutionFailure {
                    category: ToolFailureCategory::Execution,
                    message,
                }));
            }
        }
    }
    ToolResult {
        model_output,
        outcome: ToolOutcome::Inspect(InspectResult { jobs }),
    }
}

fn execute_job(
    workspace: &WorkspaceRoot,
    request: &InspectJobRequest,
) -> Result<InspectCommandOutput, String> {
    match request {
        InspectJobRequest::Read(request) => read::execute(workspace, request),
        InspectJobRequest::List(request) => list::execute(workspace, request),
        InspectJobRequest::Stat(request) => stat::execute(workspace, request),
        InspectJobRequest::Bytes(request) => bytes::execute(workspace, request),
        InspectJobRequest::ByteSearch(request) => bytes::execute_search(workspace, request),
        InspectJobRequest::Strings(request) => strings::execute(workspace, request),
        InspectJobRequest::Elf(request) => elf::execute(workspace, request),
        InspectJobRequest::Search(request) => search::execute(workspace, request),
        InspectJobRequest::Which(request) => which::execute(request),
        InspectJobRequest::Check(request) => cargo::check(workspace, request),
        InspectJobRequest::Test(request) => cargo::test(workspace, request),
        InspectJobRequest::Ps(request) => process::execute(request),
        InspectJobRequest::Pwd => Ok(InspectCommandOutput {
            model: format!("{}\n", workspace.path().display()),
            result: InspectJobSuccess::Pwd {
                path: workspace.path().display().to_string(),
            },
        }),
    }
}

fn rejected_result(message: String) -> ToolResult {
    ToolResult {
        model_output: message.clone(),
        outcome: ToolOutcome::Failed(ToolExecutionFailure {
            category: ToolFailureCategory::InvalidInput,
            message,
        }),
    }
}

fn command_start(line: &str) -> bool {
    let command = line.split_whitespace().next().unwrap_or_default();
    matches!(
        command,
        "pwd"
            | "list"
            | "stat"
            | "bytes"
            | "byte-search"
            | "strings"
            | "elf"
            | "search"
            | "which"
            | "check"
            | "test"
            | "ps"
            | "read"
    )
}

fn parse_range(value: &str) -> Result<LineRange, String> {
    if let Some((start, count)) = value.split_once('+') {
        let start_line = shell::parse_positive_usize_value(start).map_err(|_| {
            "failed to parse `inspect` input: range start must be a positive integer".to_string()
        })?;
        let line_count = shell::parse_positive_usize_value(count).map_err(|_| {
            "failed to parse `inspect` input: range count must be a positive integer".to_string()
        })?;
        return Ok(LineRange {
            start_line,
            line_count,
        });
    }
    if let Some((start, end)) = value.split_once('-') {
        let start_line = shell::parse_positive_usize_value(start).map_err(|_| {
            "failed to parse `inspect` input: range start must be a positive integer".to_string()
        })?;
        let line_count = if end.eq_ignore_ascii_case("end") {
            usize::MAX
        } else {
            let end = shell::parse_positive_usize_value(end).map_err(|_| {
                "failed to parse `inspect` input: range end must be a positive integer or `end`"
                    .to_string()
            })?;
            if end < start_line {
                return Err("failed to parse `inspect` input: range end must be >= start".into());
            }
            end - start_line + 1
        };
        return Ok(LineRange {
            start_line,
            line_count,
        });
    }
    Err("failed to parse `inspect` input: range must be `start+count` or `start-end`".into())
}
fn resolve(workspace: &WorkspaceRoot, value: &str) -> Result<(String, PathBuf), String> {
    let relative = workspace
        .relative_path(value)
        .map_err(|e| format!("inspect: invalid path `{value}`: {e}"))?;
    let name = relative.as_str().to_owned();
    let abs = workspace.path().join(relative.as_str());

    // If the path already exists, return it directly.
    if abs.exists() {
        return Ok((name, abs));
    }

    // Path does not exist — try to suggest a correction.
    if let Some(correction) = crate::path_correction::suggest_correction(workspace.path(), &name) {
        let mut msg = format!("inspect: path `{name}` does not exist");
        msg.push_str(&format!("\nDid you mean: `{}`?", correction.suggested));
        if !correction.listing.is_empty() {
            msg.push_str(&format!("\nFiles in `{}`:", correction.deepest_prefix,));
            for entry in &correction.listing {
                msg.push_str(&format!("\n  {entry}"));
            }
            if correction.omitted_entries > 0 {
                msg.push_str(&format!(
                    "\n  [... {} additional entries omitted]",
                    correction.omitted_entries
                ));
            }
        }
        msg.push('\n');
        return Err(msg);
    }

    Err(format!("inspect: path `{name}` does not exist\n"))
}

pub(crate) fn positive(value: &str, command: &str) -> Result<usize, String> {
    value
        .parse()
        .ok()
        .filter(|v| *v > 0)
        .ok_or_else(|| format!("inspect {command}: expected a positive integer"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_path_fallback_bounds_files_in_workspace_listing() {
        let root =
            std::env::temp_dir().join(format!("inspect-path-fallback-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        for index in 0..40 {
            std::fs::write(root.join(format!("file-{index:02}.txt")), "").unwrap();
        }
        let workspace = WorkspaceRoot::open(&root).unwrap();

        let error = resolve(&workspace, "file-99.txt").unwrap_err();

        assert!(error.contains("Files in `.`:"));
        assert_eq!(
            error
                .lines()
                .filter(|line| line.starts_with("  file-"))
                .count(),
            25
        );
        assert!(error.contains("[... 15 additional entries omitted]"));
        let _ = std::fs::remove_dir_all(root);
    }
}
